export const seedAdmin = {
  email: "admin@mindscreen.app",
  password: "123456",
};

export const seedUsers = [
  {
    id: 1,
    name: "Aisha Noor",
    age: 21,
    role: "Student",
    device: "Android + Laptop",
    wellbeingScore: 78,
    riskLevel: "Moderate",
    screenTimeHours: 4.8,
    focusHours: 3.2,
    sleepHours: 6.7,
    unlocks: 49,
    scrollingHours: 1.9,
    typingSpeed: 53,
    heartRate: 82,
    hydration: 72,
    mainIssue: "Late-night social scrolling is reducing sleep consistency.",
    tags: ["sleep", "social"],
    goals: { maxScreenTime: 4.5, minSleep: 7, minFocus: 3.5 },
    recommendations: [
      "Turn on sleep mode at 10:30 PM.",
      "Limit social apps to 25 minutes after 9 PM.",
      "Run one 45-minute focus session before entertainment use.",
    ],
    weeklyTrend: [62, 64, 69, 66, 72, 76, 78],
    appUsage: [
      { label: "Social", minutes: 125, color: "#8b5cf6" },
      { label: "Study", minutes: 102, color: "#10b981" },
      { label: "Video", minutes: 58, color: "#0ea5e9" },
      { label: "Other", minutes: 31, color: "#f59e0b" },
    ],
  },
  {
    id: 2,
    name: "Omar Khalid",
    age: 22,
    role: "Student",
    device: "iPhone + MacBook",
    wellbeingScore: 85,
    riskLevel: "Low",
    screenTimeHours: 3.9,
    focusHours: 4.1,
    sleepHours: 7.4,
    unlocks: 34,
    scrollingHours: 1.1,
    typingSpeed: 58,
    heartRate: 76,
    hydration: 80,
    mainIssue: "Frequent messaging interruptions affect deep work sessions.",
    tags: ["focus", "notifications"],
    goals: { maxScreenTime: 4, minSleep: 7.2, minFocus: 4 },
    recommendations: [
      "Mute messaging apps during your two main study blocks.",
      "Keep one 15-minute break between long sessions.",
      "Use app grouping so social tools stay off the first home screen.",
    ],
    weeklyTrend: [70, 73, 77, 79, 82, 84, 85],
    appUsage: [
      { label: "Study", minutes: 148, color: "#10b981" },
      { label: "Messaging", minutes: 63, color: "#0ea5e9" },
      { label: "Social", minutes: 46, color: "#8b5cf6" },
      { label: "Other", minutes: 28, color: "#f59e0b" },
    ],
  },
  {
    id: 3,
    name: "Sara Ahmed",
    age: 20,
    role: "Student",
    device: "Android",
    wellbeingScore: 61,
    riskLevel: "High",
    screenTimeHours: 6.1,
    focusHours: 2,
    sleepHours: 5.9,
    unlocks: 71,
    scrollingHours: 2.8,
    typingSpeed: 46,
    heartRate: 91,
    hydration: 58,
    mainIssue: "Entertainment usage is crowding out study time and sleep recovery.",
    tags: ["addiction", "sleep", "focus"],
    goals: { maxScreenTime: 4.5, minSleep: 7, minFocus: 3 },
    recommendations: [
      "Cut entertainment apps by 20 minutes per day this week.",
      "Start each day with study-first usage before social media.",
      "Place the phone away from the bed and enable bedtime reminders.",
    ],
    weeklyTrend: [49, 54, 56, 58, 60, 63, 61],
    appUsage: [
      { label: "Video", minutes: 138, color: "#0ea5e9" },
      { label: "Social", minutes: 110, color: "#8b5cf6" },
      { label: "Study", minutes: 72, color: "#10b981" },
      { label: "Other", minutes: 46, color: "#f59e0b" },
    ],
  },
];

export const activityTemplates = [
  { type: "screen", tone: "sky", title: "Screen spike detected", detail: "Entertainment usage crossed the hourly baseline." },
  { type: "focus", tone: "green", title: "Focus streak complete", detail: "A protected focus block was completed without interruptions." },
  { type: "alert", tone: "amber", title: "Break reminder sent", detail: "The system pushed a posture and hydration reminder." },
  { type: "sleep", tone: "violet", title: "Sleep protection enabled", detail: "Wind-down mode was suggested before bedtime." },
];
